apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  storageClassName: hostpath
  hostPath:
    path: /Users/marc/mnt

