apiVersion: v1
kind: Service
metadata:
  labels:
    app: module
    env: {{.Release.Namespace}}
  name: module-service  # Hier verwijst de Ingress naar
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    # Selector koppelt de service aan de deployment met betreffende label
    customer: kadaster
    app: ozon
    env: {{.Release.Namespace}}
  sessionAffinity: None
  type: ClusterIP
