apiVersion: v1
kind: ConfigMap
metadata:
  # Als de naam gelijk is aan de naam van de applicatie (in application.properties) dan wordt deze onder K8S automatisch geladen
  # (mits Spring Cloud Kubernetes is geladen)
  name: kubernetes-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  # Hier wordt een default value geladen, die door Kubernetes zou moeten worden overschreven (nog ongetest)
  valueFromKubernetes: value from configMap2
