apiVersion: v1
kind: Service
metadata:
  labels:
    app: module1
  name: module1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: module1
  sessionAffinity: None
  type: ClusterIP
