apiVersion: v1
kind: Service
metadata:
  labels:
    app: module
  name: module-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    # Selector koppelt de service aan de deployment met betreffende label
    app: module-service-deployment
  sessionAffinity: None
  type: ClusterIP
