apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: module-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:228991124303:certificate/887af1da-47a6-43ad-9920-8ebf08bacf2b
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 81}, {"HTTPS":443}]'
    # dualstack werkt alleen als de subnets ook dualstack zijn
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/group.name: module
    external-dns.alpha.kubernetes.io/hostname: module1.liberaalgeluid.nl, liberaalgeluid.nl
  labels:
    app: module-service
spec:
  rules:
    - host: module1.liberaalgeluid.nl
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: module-service
                port:
                  name: http
    - host: liberaalgeluid.nl
      http:
        paths:
          - path: /module1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: module-service
                port:
                  number: 8080
    - http:
        paths:
          - path: /module1/*
            pathType: Exact
            backend:
              service:
                name: module-service
                port:
                  number: 8080
