apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: module1-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: module1
spec:
  rules:
    - http:
        paths:
          - path: /module1(/|$)(.*)
            backend:
              serviceName: module1-nodeport
              servicePort: 8080
