apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: module1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: my-pv
  storageClassName: hostpath
